Packed Update Test
ss14-harmony/space-station-14 pull request #103
Opened 2024-10-03 23:37 UTC by spanky-spanky

## About the PR
Added modified version of Packed and removed previous Packed from the map pool for testing purposes on Harmony.

2024-10-03 23:44 UTC, FluffMe requested changes
Build will fail on Integration tests.

Add `Packed2` to `Content.IntegrationTests/Tests/PostMapInitTest.cs`

2024-10-03 23:49 UTC, FluffMe submitted a review, later dismissed

2024-10-04 00:03 UTC, FluffMe approved these changes
Obviously, not reading the huge YAML.
But it launched OK in game and passed the checks.Other files are OK too.

Approved.

2024-10-04 00:05 UTC, spanky-spanky commented
I am going to delete this eventually anyways so not a big deal.

2024-10-04 00:05 UTC, merged