Added DM01 Entryway and deathmatch PROMOD preset
ss14-harmony/space-station-14 pull request #127
Opened 2024-10-19 00:27 UTC by Unisol

Requires #31178
## About the PR

Added a (second) deathmatch map, based on a classic map from a different age. Added a deathmatch PROMOD preset (dmpm, deathmatchpromod), that works exactly like regular deathmatch but with guns.

## Why / Balance

One map is good, more is better. In addition, existing deathmatch map (Meteor Arena) is not very well fit for small arms combat, being designed for melee combat. PROMOD deathmatch is meant to replicate typical firefight that happens in SS14 but in deathmatch sandbox.

## Technical details

N/A

## Media

![dm01-entryway-0](https://github.com/user-attachments/assets/1c44bd16-e2fa-4b61-bb90-6b19dce09c32)

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

N/A

**Changelog**

:cl:
- add: added deathmatch map DM01 Entryway
- add: added deathmatch PROMOD preset

2024-10-20 02:34 UTC, KeldWolf commented
This could be interesting for future Funday Sunday stuff. I can't imagine it facilitate very many players. Curious what others have to say about it.

2024-10-20 07:15 UTC, Unisol commented
There's enough spawn points here for about 10 players, but it's hard to say how many can be comfortably packed in here. I'd guess about 5-7 people with guns can fit in this map without overcrowding.

2024-10-21 15:07 UTC, FluffMe requested changes
One minor request to relocate.

2024-10-21 15:07 UTC, FluffMe commented on Resources/Prototypes/Maps/arenas.yml
> +            Passenger: [ -1, -1 ]
Please move this gameMap to `Resources/Prototypes/_Harmony/Maps/arenas.yml`

2024-10-24 00:22 UTC, Unisol commented
Issues addressed

2024-10-24 08:33 UTC, spanky-spanky commented
Looks good, I’ll let Keld make the call to merge if we went this for Sunday Funday stuff but otherwise I approve.

2024-10-30 18:11 UTC, FluffMe approved these changes
Mostly admeme, noone objects. Merged

2024-10-30 18:11 UTC, merged