Added a new lobbyscreen
ss14-harmony/space-station-14 pull request #167
Opened 2024-11-08 22:00 UTC by elisarek

## About the PR
Added a new lobby screen

## Technical details

-Added survivalharmony.webp and its associated YML file into /Resources/Textures/LobbyScreens.
-Added survivalharmony.webp to lobbyscreens.yml
-Added survivalharmony.webp to attributions.yml in /Resources/Textures/LobbyScreens under the CC-BY-NC-SA-4.0 license.
## Media

![Ss14_Harmony](https://github.com/user-attachments/assets/d75f3b4e-5728-45e6-9d61-fe0ba40cd66d)

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: Added "Survival Harmony" lobby art by Logan Avery

2024-11-08 23:23 UTC, FluffMe requested changes
Almost there! Couple of changes pending.

Great art, thank you for doing this.

2024-11-08 23:23 UTC, FluffMe commented on Resources/Textures/LobbyScreens/survivalharmony.webp.webp
File name is incorrect.
Please rename to `survivalharmony.webp`
(currently is `survivalharmony.webp.webp`)

2024-11-08 23:23 UTC, FluffMe commented on Resources/Textures/LobbyScreens/attributions.yml
> +  source: "https://github.com/space-wizards/space-station-14"
Should be `https://github.com/ss14-harmony/space-station-14` unless it's from upstream

2024-11-09 00:29 UTC, elisarek commented on Resources/Textures/LobbyScreens/survivalharmony.webp.webp
🤦no clue how that happened, many thanks.

2024-11-09 00:30 UTC, FluffMe approved these changes
Looks good. ~~Will merge after test pass~~ I am not the art code owner as I have no taste. So we wait for Keld.

Please draw more stuff!

2024-11-10 23:35 UTC, KeldWolf approved these changes
Approved

2024-11-10 23:36 UTC, merged