Ducky galoshes
ss14-harmony/space-station-14 pull request #168
Opened 2024-11-08 22:18 UTC by Unisol

## About the PR
Added yellow ducky galoshes, art courtesy whythelettuce on discord. Crafting recipe takes two toy ducks, one galoshes and one of either crazy glue or space glue.

## Technical details
I had to add tag component to ClothingShoesGaloshes entity since it doesn't have that in upstream; this is the only change not confined to _Harmony subfolders.

## Media
![SS14 Loader_2wXG6LfgFy](https://github.com/user-attachments/assets/e48f84ed-eb34-45fd-adcf-1311f1fd9744)

[Discussion thread](https://discord.com/channels/1139716325627932682/1303402658828128340)

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: added rubber ducky galoshes. Quack Quack!

2024-11-09 00:18 UTC, FluffMe requested changes
Awesome work!!!

Couple of changes are needed, couple are optional.

2024-11-09 00:18 UTC, FluffMe commented on Resources/Prototypes/Entities/Clothing/Shoes/specific.yml
> +    - ClothingShoesGaloshes
This change should be properly commented.

Something like `# Harmony change. Tag component is needed for ducky galoshes` on the `type` line.

2024-11-09 00:18 UTC, FluffMe commented on Resources/Prototypes/_Harmony/tags.yml
> +
Can add a comment that this is added to upstream `ClothingShoesGaloshes` entity for ducky galoshes implementation. Optional.

2024-11-09 00:18 UTC, FluffMe commented on Resources/Prototypes/_Harmony/Recipes/Construction/Graphs/clothing/ducky_galoshes.yml
Three `doAfters` can be slightly simplified as follows:
- Remove all three.
- Add a `doAfter: 2` to last glue tag.

Will be 2 seconds, and work basically the same.

Super optional, as achieves the same thing, and both ways of doing this are totally fine.

2024-11-10 00:33 UTC, Unisol commented on Resources/Prototypes/_Harmony/Entities/Clothing/Shoes/specific.yml
> +  id: ClothingShoesDuckyGaloshes
I'd personally rather keep the same name, just to confuse people.

2024-11-10 00:47 UTC, Unisol commented
Addressed most concerns.

2024-11-10 01:08 UTC, FluffMe commented on Resources/Prototypes/_Harmony/Entities/Clothing/Shoes/specific.yml
> +  id: ClothingShoesDuckyGaloshes
That's funny!
Agreed. Didn't think about that

2024-11-10 01:22 UTC, FluffMe approved these changes

2024-11-10 02:47 UTC, FluffMe submitted a review, later dismissed
Bug found.

Sorry for not catching this in the first round :(

2024-11-10 02:47 UTC, FluffMe commented on Resources/Prototypes/_Harmony/Entities/Clothing/Shoes/specific.yml
There is a bug due to inheritance from `ClothingShoesGaloshes`.

New entity inherits the `ClothingShoesGaloshes` tag making it a viable material for crafting of ducky galoshes.
It is possible to make ducky galoshes from 2 duckies, ducky galoshes, and glue. This will basically just eat your duckies and glue and achieve nothing.

While it's an edge case, it can happen if you try to make a second pair for someone.

Proposed fixes:
- Adding tag component to `ClothingShoesDuckyGaloshes` with empty tags will solve the issue. Preferred. 
```yaml
  - type: Tag
    tags: []
```
- making the parent `ClothingShoesBase` and defining all the needed components in `ClothingShoesDuckyGaloshes` would solve the issue. Not preferred, as any balancing to galoshes will skip the ducky ones.
- Won't fix. Just accept the quirk.

Your call on how to address this. I am generally fine with either, but first option is preferred.
Maybe you have a solution i didn't think about too.

2024-11-10 02:56 UTC, Unisol commented on Resources/Prototypes/_Harmony/Entities/Clothing/Shoes/specific.yml
I agree, setting tag explicitly is the best option here. I'll make the change.

2024-11-10 03:28 UTC, FluffMe requested changes
Last stretch:

- With all this tag shenanigans we are losing the parent->parent tags of  `ClothingShoesBase`
https://github.com/Unisol/ss14/blob/3d31f7bcfbc0c3c1c2a5405920ac73f8db6fdb44/Resources/Prototypes/Entities/Clothing/Shoes/base_clothingshoes.yml#L22

    While `ClothMade` can be dropped, `WhitelistChameleon` should be fun, IMO.
    Chameleon is also important for regular galoshes, as right now they are removed  from chameleon gear.

    Proposed fix:
    Add `WhitelistChameleon` tag to `ClothingShoesGaloshes` and `ClothingShoesDuckyGaloshes`

- Tag `ClothingShoesDuckyGaloshes` is unused and should be removed. If you don't want to set `WhitelistChameleon` to Ducky Galoshes, just assign empty tags with `tags: []`

Sorry for bombarding you with change requests! I should have spotted all of those in the beginning.

2024-11-10 22:40 UTC, Unisol commented
> Tag `ClothingShoesDuckyGaloshes` is unused and should be removed.

I disagree; it's unused *at the moment*, in the future there's a possibility of adding further crafting recipes that use these galoshes, and I'd rather have tag be there for that.

Other requests are reasonable, I'll make the changes.

2024-11-10 23:56 UTC, FluffMe reviewed
I'll let keld decide on leaving unused code in.

2024-11-11 01:00 UTC, DieselMohawk requested changes
Slight inconsistencies between the two side sprites.
![image](https://github.com/user-attachments/assets/e0c7a25b-9080-4da9-8cc3-42588a0958eb)

2024-11-11 04:44 UTC, Unisol commented
Whythelettuce supplied a new version of galoshes sprite, it's been added to PR.

2024-11-11 06:03 UTC, DieselMohawk approved these changes

2024-11-11 06:04 UTC, DieselMohawk commented
Alrighty, looks good to me. Good work to Unisol and Whythelettuce for their respective work.

2024-11-13 15:57 UTC, KeldWolf approved these changes
Approved. I'm late to the discussion party. But, unused for now code usually would live on a non-master branch until it's ready to be used. But, it's less a hard rule and more a best practice thing. Anyhow. Ducky feet time!

2024-11-13 15:58 UTC, merged