Janitorial toolbox
ss14-harmony/space-station-14 pull request #171
Opened 2024-11-10 00:13 UTC by Unisol

## About the PR
Added janitorial toolbox. It's purple and has following guaranteed items:
* screwdriver
* wrench
* plunger
* network configurator
* welder
* welding mask

Following items have low chance to spawn:
* Gin
* Rubber ducky

## Why / Balance
Burdman asked for one on discord, I asked - why not?

## Technical details
Changes to non-harmony files: edited ClosetJanitorFilled entry in Resources/Prototypes/Catalog/Fills/Lockers/service.yml to add janitorial toolbox spawn to janitor's closet.

## Media
![SS14 Loader_08M2o6f8UI](https://github.com/user-attachments/assets/46593ac5-6d56-4004-a0cc-d3ea606b090b)
![SS14 Loader_9ODQgKhLIN](https://github.com/user-attachments/assets/0c0bd862-5818-406a-8269-74f21ce5cef5)
![SS14 Loader_tlsTLvYuUw](https://github.com/user-attachments/assets/127aaf1f-687c-4ff3-9585-cc8da2034236)

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added purple toolbox with a little extra something to help janitor through his day

2024-11-10 03:50 UTC, FluffMe requested changes
Just couple of things:
Missing comment for licensing change to AGPL (mandatory change) and minor indentation issue in JSON (optional change).

This is an awesome addition!

2024-11-10 03:50 UTC, FluffMe commented on Resources/Prototypes/Catalog/Fills/Lockers/service.yml
> +      - id: ToolboxJanitorialFilled
Upstream file needs a `Harmony change` comment.

2024-11-10 03:50 UTC, FluffMe commented on Resources/Textures/_Harmony/Objects/Tools/Toolboxes/toolbox_purple.rsi/meta.json
> +        "name": "icon-open"
Over-indented. Not very important.

2024-11-10 22:58 UTC, Unisol commented
Tell me more about the "licensing change to AGPL", I'm not quite sure what you mean by this.

2024-11-10 23:43 UTC, FluffMe submitted a review, later dismissed

2024-11-10 23:48 UTC, FluffMe approved these changes

2024-11-11 01:05 UTC, DieselMohawk approved these changes
Looks good. Good job.

2024-11-11 01:05 UTC, merged