Captain's Turtleneck and skirt variant
ss14-harmony/space-station-14 pull request #186
Opened 2024-11-14 16:15 UTC by thesaladmancer

## About the PR

Added new Turtleneck jumpsuit and jumpskirt to the captain's dresser and loadout.

## Why / Balance

I thought it would be nice for Captain to get a turtleneck outfit to fit with every other command member, since it was kinda strange that they didn't have one before (HoP as well, but they recently got one too.)

## Technical details

Added sprites for the jumpsuit and jumpskirt in `capturtleneck.rsi` and `capturtleskirt.rsi`, along with their associated `meta.json` files.
Added entries for the jumpsuit and jumpskirt to `jumpsuits.yml` and `jumpskirts.yml` respectively.
Added the jumpsuit and jumpskirt to the Captain's dresser in `dressers.yml`.
Added the jumpsuit and jumpskirt to the Captain's `captain.yml` file in `/Resources/Prototypes/_Harmony/Loadouts/Jobs/Command`
Added the jumpsuit and jumpskirt to the Captain's jumpsuit loadout group in `loadout_groups.yml`.

## Media

![turtleneck](https://github.com/user-attachments/assets/f35ebd8f-a770-41f7-a474-5dc42a8c3d9e)
![turtleskirt](https://github.com/user-attachments/assets/2dfa09b2-7cf8-4e46-aa25-4392a03e13fc)
![image](https://github.com/user-attachments/assets/2fcb60a9-d7af-429d-b8e0-fc89704aa025)

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: Added Captain's Turtleneck and skirt variant.

2024-11-14 16:55 UTC, thesaladmancer commented
> I'd move it out of the dresser and into the uniform printer, same as our hop turtleneck and skirt.

That's a pretty good idea actually, I wasn't aware of the HoP turtlenecks being in the uniform printer as the main method of obtaining them during the round. I should still keep it as a loadout option too, yeah?

2024-11-14 16:56 UTC, FluffMe commented
> > I'd move it out of the dresser and into the uniform printer, same as our hop turtleneck and skirt.
> 
> That's a pretty good idea actually, I wasn't aware of the HoP turtlenecks being in the uniform printer as the main method of obtaining them during the round. I should still keep it as a loadout option too, yeah?

Correct! You can refer to #104 and #108  for implementation

2024-11-14 16:57 UTC, FluffMe requested changes
Entities and textures need relocating to other folders.

Once relocation is complete, and build error is fixed via uniform printer, I'll do another more thorough pass. This one is just files location without inspecting the entities.

2024-11-14 16:57 UTC, FluffMe commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpskirts.yml
> +
This entity should be moved to `Resources/Prototypes/_Harmony/Entities/Clothing/Uniforms/jumpskirts.yml`

2024-11-14 16:57 UTC, FluffMe commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/capturtleskirt.rsi/meta.json
This RSI and all its textures in it should be relocated to `Resources/Textures/_Harmony/Clothing/Uniforms/Jumpskirt/capturtleskirt.rsi`

2024-11-16 00:37 UTC, FluffMe approved these changes
Code looks good.

Thank you very much!

Additional screenshots for other reviewers:
**Lathe**
![image](https://github.com/user-attachments/assets/40984c1f-6b6a-44bb-897b-614c38b1bbcf)
**Loadout**
![image](https://github.com/user-attachments/assets/9c5c94bb-707e-4b2d-a5c0-b89174eedfbc)
**Item description**
![image](https://github.com/user-attachments/assets/3d603b7e-2164-4161-8367-0dd43bf71ab3)

2024-11-16 01:40 UTC, DieselMohawk approved these changes
Looks good

2024-11-16 01:40 UTC, merged