RSC rifle crate as cargo purchase
ss14-harmony/space-station-14 pull request #189
Opened 2024-11-16 21:56 UTC by Unisol

## About the PR
Added RSC Model 1917, a Nanotrasen-approved great war rifle. Available for purchase for supply department. Packed by senile veteran of six stellar wars who can't quite remember how many rifles and stripper clips should go in one crate; your mileage will vary.

## Why / Balance
Syndicate has cheap mass infantry option, and now Nanotrasen does too. Meant to be a cheap way to arm large amounts of people with questionable quality guns. RSC 1917 is mechanically identical to Mosin Nagant.

Cost: one crate goes for 2000$, with one rifle costing $400 and one clip costing $5. Anywhere between 2 and 5 rifles per crate, with anywhere between 4 and 42 clips mean that total cost varies between $1020 and $2210. This ensures cargo can't reliably resell these at a profit.

## Technical details

## Media

TBA

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: added RSC Model 1917 for purchase in supply dept
- add: added stripper clips with .30 ammo to secfab

2024-11-17 06:54 UTC, DieselMohawk approved these changes
Good sprites.

I have no idea if we should reference real world locations and events with this rifle, even the name is a bit too historically accurate for the SS14 vibe, if you get what I mean.

Anyways, good sprites.

2024-11-17 15:53 UTC, FluffMe commented
@Unisol test fail is real

`TestSufficientSpaceForEntityStorageFill` fails with `CrateArmoryRSC storage fill is too large.`

2024-11-17 15:59 UTC, FluffMe commented on Resources/Prototypes/_Harmony/Catalog/Fills/Crates/armory.yml
> +        # Lost is a dogshit show
![image](https://media2.giphy.com/media/2yUoIisEPpr0I/200w.gif)

2024-11-17 16:07 UTC, FluffMe requested changes
- Test fail should be addressed (if amount of rifles/ammo changes significantly price may need to be reduced).
- Lost comment, while appreciated and agreed with, should be removed.
- Cargo access on the crate will finally prevent slamming it with pickaxe like idiots. But it differs from other gun purchases. If that's an intended change, I agree with this, but please test if it overwrites `access: [["Armory"]]` of `CrateWeaponSecure` and if Armory access should be added (maybe instead of security even, who knows. No idea how it works without testing).

Thanks for this addition. Hail Cargonia!
I'll read and test this more thoroughly when changes are addressed.

2024-11-17 16:11 UTC, FluffMe commented
> I have no idea if we should reference real world locations and events with this rifle, even the name is a bit too historically accurate for the SS14 vibe, if you get what I mean.

There is a precedent with Mosin, and they have the same vibe IMO.
We also already discussed if the gun is in public domain or not, so this is also not a concern.

2024-11-17 16:13 UTC, FluffMe commented
PS: I especially dig the RNG factor of the crate XD

2024-11-17 18:13 UTC, Unisol commented
Increased CrateArmoryRSC capacity to 50; removed truthful comment; added Armory access to the crate in addition to Supply and Securty.

2024-11-17 19:28 UTC, FluffMe commented
Another test fail: `NoStaticPriceAndStackPrice`

2024-11-17 21:39 UTC, Unisol commented
No idea what this is about, I've checked crate, rifle and clip - all have only static price and not stack price.

2024-11-17 21:43 UTC, FluffMe commented
I'll debug when I get some time next week.

2024-11-17 23:17 UTC, FluffMe commented
Was a Heisentest XD

2024-11-18 00:02 UTC, DieselMohawk approved these changes

2024-11-18 02:40 UTC, FluffMe reviewed
Code is good! great job, thank you.

I'll leave it hanging for a bit for admins and Keld to pitch in, since it's a new weapon and weapon source for the crew.

2024-11-18 03:01 UTC, liltenhead commented
Considering there's an AK and a Mosin in game, I like the idea. Sprite is great looking too.

2024-11-20 19:59 UTC, FluffMe approved these changes

2024-11-20 19:59 UTC, merged