Blue Sec Update Two: Seclectric Bluegaloo
ss14-harmony/space-station-14 pull request #210
Opened 2024-11-25 07:58 UTC by BoskiYourk

## About the PR

- Added a bluesuit outfit for the detective
- Added a new bluesuit jumpsuit for the warden
- Added new hats to match the officer blue suit
- Added everything to the loadout menus and uniform printer

## Why / Balance

HoS and officers get blue suits, so why not the warden and detective too?

## Technical details

### _Harmony Namescape
Resources/Prototypes/_Harmony/Entities/Clothing/Head/hats.yml -- Adds the beret and fedora entities
Resources/Prototypes/_Harmony/Entities/Clothing/Head/soft.yml -- Adds the blue cap entity
Resources/Prototypes/_Harmony/Entities/Clothing/OuterClothing/coats.yml -- Adds the blue coat entity
Resources/Prototypes/_Harmony/Entities/Clothing/Uniforms/jumpsuits.yml -- Adds the blue warden and det suit entities
Resources/Prototypes/_Harmony/Loadouts/Jobs/Security/detective.yml -- Detective loadout options
Resources/Prototypes/_Harmony/Loadouts/Jobs/Security/security_officer.yml -- Officer loadout options
Resources/Prototypes/_Harmony/Loadouts/Jobs/Security/warden.yml -- Warden loadout options
Resources/Prototypes/_Harmony/Recipes/Lathes/clothing.yml -- Lathe recipes 
Resources/Textures/_Harmony/Clothing/Head/Hats/beret_security_blue.rsi -- Beret sprite location
Resources/Textures/_Harmony/Clothing/Head/Hats/bluefedora.rsi -- Fedora sprite location
Resources/Textures/_Harmony/Clothing/Head/Soft/secbluesoft.rsi -- Cap sprite location
Resources/Textures/_Harmony/Clothing/OuterClothing/Coats/detective_blue.rsi -- Coat sprite location
Resources/Textures/_Harmony/Clothing/Uniforms/Jumpsuit/det_blue.rsi -- Detective suit sprite location
Resources/Textures/_Harmony/Clothing/Uniforms/Jumpsuit/warden_blue.rsi -- Warden suit sprite location

### Upstream Files
Resources/Prototypes/Catalog/VendingMachines/Inventories/detdrobe.yml -- Added the detective clothes to the detdrobe
Resources/Prototypes/Catalog/VendingMachines/Inventories/secdrobe.yml -- Added the beret and cap to the secdrobe
Resources/Prototypes/Entities/Structures/Machines/lathe.yml -- IDs for clothing printer
Resources/Prototypes/Loadouts/loadout_groups.yml -- Adds the new items to the loadout menu

## Media

![Blue Det](https://github.com/user-attachments/assets/296018d4-0b3c-4bf9-8062-aacda805470a)
![Blue Ward](https://github.com/user-attachments/assets/61c14e6d-a7ca-43eb-a909-a5dfbea87ed5)
![Blue Hat](https://github.com/user-attachments/assets/dd73f91a-4f46-4d14-b140-ad65d7d81bb7)
![Blue Beret](https://github.com/user-attachments/assets/b5e70983-9736-434a-bff4-c9605d869360)

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Finished adding blue sec options for the rest of the security team.

2024-11-25 08:01 UTC, BoskiYourk commented
Not sure what's up with the HoS hat showing up as having some bits removed, so hopefully that isn't too big of a deal...

2024-11-25 09:28 UTC, DieselMohawk requested changes
Fix the icon size for the blue beret. That's likely causing the test failure.

2024-11-25 09:28 UTC, DieselMohawk commented on Resources/Textures/_Harmony/Clothing/Head/Hats/beret_security_blue.rsi/icon.png
This is the offending file, please fix.

Change from 64x64 to 32x32

2024-11-25 09:32 UTC, DieselMohawk commented on Resources/Textures/_Harmony/Clothing/Head/Hats/beret_security_blue.rsi/icon.png
On further inspection ALL of your icon files are in 64x64, please make them all 32x32.

2024-11-25 09:42 UTC, DieselMohawk commented on Resources/Prototypes/_Harmony/Loadouts/Jobs/Security/warden.yml
"Jumpsuit" misspelled as "Jumsuit" may br causing errors

2024-11-25 09:42 UTC, DieselMohawk commented on Resources/Prototypes/_Harmony/Entities/Clothing/Uniforms/jumpsuits.yml
Please replace all instances of "jumsuit" with "jumpsuit"

2024-11-25 09:49 UTC, DieselMohawk commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/secdrobe.yml
May be worthwhile to capitalize "Soft"

2024-11-26 07:01 UTC, DieselMohawk commented
Damn, test failure, time to look at it again

2024-11-26 11:52 UTC, FluffMe requested changes
```
Resources/Textures/_Harmony/Clothing/OuterClothing/Coats/detective_blue.rsi: PNG not defined in metadata: Inhand-right.png
Resources/Textures/_Harmony/Clothing/OuterClothing/Coats/detective_blue.rsi: PNG not defined in metadata: Equipped-OUTERCLOTHING.png
Resources/Textures/_Harmony/Clothing/OuterClothing/Coats/detective_blue.rsi: equipped-OUTERCLOTHING: failed to open state equipped-OUTERCLOTHING.png
Resources/Textures/_Harmony/Clothing/OuterClothing/Coats/detective_blue.rsi: inhand-right: failed to open state inhand-right.png
```
While files for states are present in RSI, the states and file names are case sensitive.

Inhand-right.png and Equipped-OUTERCLOTHING.png should be renamed (uncapitalize first letter of the file name).

2024-11-27 06:36 UTC, DieselMohawk submitted a review, later dismissed
Turns out I forgot to send my review, looks good now though

2024-11-27 06:37 UTC, DieselMohawk commented
Me when I don't send my pending reviews by accident :)

2024-11-27 18:10 UTC, FluffMe requested changes
Only two minor changes, and it's good to go!
Thank you very much for working on this.

2024-11-27 18:10 UTC, FluffMe commented on Resources/Prototypes/_Harmony/Entities/Clothing/Uniforms/jumpsuits.yml
> +  name: Warden's Blue Suit
Please make the name all lowercase to match the names of other items in the game

2024-11-27 22:51 UTC, BoskiYourk commented
Capitalization is fixed, so this will hopefully be the last commit needed.

2024-11-28 00:39 UTC, DieselMohawk approved these changes

2024-11-28 07:11 UTC, FluffMe approved these changes

2024-11-28 07:12 UTC, merged