Feature/smugglers satchel
ss14-harmony/space-station-14 pull request #228
Opened 2024-12-07 14:08 UTC by Ermucat

## About the PR
Added the smugglers satchel, a new syndiecate item that can fit under floor tiles

## Why / Balance
New way to hide loot, it can also be seen with tray so its not to powerful

## Technical details
=Added entities to list

## Media
See below I guess?

## Requirements

- [X ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X ] I have added media to this PR or it does not require an ingame showcase

https://github.com/user-attachments/assets/f07adfc9-c5be-4e4b-98e9-8b1e63ac01eb

.

## Breaking changes

**Changelog**

2024-12-07 22:29 UTC, Unisol commented
Should it be considered contraband? If it's supposed to be clandestine backpack that isn't illegal by itself, I'd suggest making sprite the same as base satchel; otherwise, it's trivial to metagame.

Alternatively, give it a non-uplink way of obtaining (such as adding it to maints locker spawn pool); this way you won't be immediately valid if you have this.

2024-12-07 23:26 UTC, Ermucat commented
Oh shoot your right let me figure out how to do that real quick

2024-12-08 00:41 UTC, RotEmpress commented
Out of curiousity, Ermu. what's your thoughts on allowing Smugglers Satchel to be spawned around the station underneath tiles? I feel like if we're basing it off of TG why not allow that to be a possibility? Or did you just want the feature in first, more things later?

2024-12-08 00:52 UTC, Ermucat commented
I know there is an upstream Pr that adds that, I see no problem in having them spawn randomly, other than my version being syndie contraband

2024-12-08 17:08 UTC, FluffMe requested changes

2024-12-08 17:08 UTC, FluffMe commented on Resources/Locale/en-US/store/uplink-catalog.ftl
> +uplink-smuggler-satchel-desc = A satchel that can fit under station tiles.
These loc strings should be introduced in `Resources/Locale/en-US/_Harmony/store/uplink-catalog.ftl` instead.

2024-12-08 17:08 UTC, FluffMe commented on Resources/Prototypes/Entities/Clothing/Back/satchel.yml
> +  - type: Appearance
This entity should be introduced in `Resources/Prototypes/_Harmony/Entities/Clothing/Back/satchel.yml` instead.

2024-12-08 17:08 UTC, FluffMe commented on Resources/Textures/Clothing/Back/Satchels/smuggler.rsi/meta.json
This RSI and all sprites in it should be relocated to `Resources/Textures/_Harmony/Clothing/Back/Satchels/smuggler.rsi`

2024-12-08 17:11 UTC, FluffMe commented
The changelog entry in the PR request seems to be commented out. Please adjust the description until it's properly showing.

2024-12-08 17:15 UTC, FluffMe commented on Resources/Prototypes/Entities/Clothing/Back/satchel.yml
> +  - type: Appearance
Additionally, `name` should be lowercase to match every other item name in the game.

2024-12-08 17:16 UTC, FluffMe commented on Resources/Locale/en-US/store/uplink-catalog.ftl
> +uplink-smuggler-satchel-desc = A satchel that can fit under station tiles.
Additionally, `
uplink-smuggler-satchel-name` should be lowercase to match every other item name in the game.

2024-12-08 17:17 UTC, FluffMe commented
Test fail is real:

```
   Failed UninitializedSaveTest [11 s]
  Error Message:
   Prototype ClothingSatchelSmugglers gains a component on spawn: CollideOnAnchor
```

2024-12-10 11:29 UTC, FluffMe submitted a review, later dismissed

2024-12-10 11:33 UTC, DieselMohawk approved these changes

2024-12-15 17:13 UTC, FluffMe approved these changes

2024-12-15 18:14 UTC, DieselMohawk approved these changes

2024-12-15 18:21 UTC, merged