Adding more ways to obtain rubber duckies
ss14-harmony/space-station-14 pull request #229
Opened 2024-12-08 03:16 UTC by Ermucat

## About the PR
Added more ways to obtain rubber duckies

## Why / Balance
The lack of rubber duckies in space station 14 has been a disheartening sorrow of mine for too long. In my profound wisdom I am pushing this PR so that we can make space station 14 great again. 

## Technical details
More stuff in catalog and crates
## Media

## Requirements

- [ x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
None 👍 

**Changelog**

2024-12-08 03:18 UTC, spanky-spanky submitted a review, later dismissed

2024-12-08 17:02 UTC, FluffMe requested changes

2024-12-08 17:02 UTC, FluffMe commented on Resources/Prototypes/_Harmony/Catalog/Fills/Items/toolboxes.yml
> +        amount: 2
This gives free Ducky Galoshes (https://github.com/ss14-harmony/space-station-14/pull/168) to any janitor with a toolbox and galoshes. I want the duckie hunt for duckie galoshes to still be at least a minor challenge and not just round start get.

@Unisol please pitch in.

2024-12-08 17:12 UTC, FluffMe commented
The changelog entry in the PR request seems to be commented out. Please adjust the description until it's properly showing.

2024-12-08 17:22 UTC, FluffMe commented on Resources/Prototypes/_Harmony/Catalog/Fills/Items/toolboxes.yml
> +        amount: 2
Additionally, it already has a chance to spawn the duck on line 26:

```yaml
      - id: ToyRubberDuck
        prob: 0.15
```

2024-12-09 10:08 UTC, FluffMe approved these changes

2024-12-10 11:27 UTC, FluffMe commented
@Ermucat This already has an approval review by me from yesterday. No need to re-request it, if no further changes were made

2024-12-15 17:04 UTC, merged