Ports new syndiecate objective "teach a lesson" from https://github.com/DeltaV-Station/Delta-v/pull/2184
ss14-harmony/space-station-14 pull request #232
Opened 2024-12-11 22:21 UTC by Ermucat

## About the PR

Ported https://github.com/DeltaV-Station/Delta-v/pull/2184 from deltaV to harmony(Is ported the right word? I guess it is kinda stealing that might be frowned apon idk)
## Why / Balance

Currently the Kill or Maroon objective is the only way of doing murder within your objectives, but with the limitation that the murdered one must be permanant killed. This system CAN be anti-fun for the victim and the murderer, I dont think it should be removed but providing a alternative I feel is needed
## Technical details

Added new folder to Harmony/Locale/En-us
Added Teachalessoncomponent
added Teachalessonconditionsystem
added things to traitor objective ymls
## Media

https://github.com/user-attachments/assets/83a55be5-c2e6-454d-a914-e7e88d5414e4

## Requirements

- [ X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added new syndiecate objective, Teach someone a lesson
-->

2024-12-11 22:52 UTC, FluffMe requested changes
- When porting Delta V or other fork content, please preserve the `DeltaV` namespace as `_DeltaV`.
- Additionally, try to trace any changes to the feature after initial PR and implement them too.
- Additionally, entities from `base_objectives.yml` and `traitor.yml` can be moved to the `_Harmony` and/or `_DeltaV`.

I will do a more thorough review once these points are addressed.

Thank you for working on this! Adding Admin input label while I am at it.

2024-12-11 23:05 UTC, spanky-spanky commented
There has been very recent admin discussion of wanting more diverse objectives so the admin consensus will probably be yes.

2024-12-11 23:18 UTC, Ermucat commented
@FluffMe 
Could you ellaborate on what preserving the namespace is?

2024-12-11 23:20 UTC, FluffMe commented
> @FluffMe 
> Could you ellaborate on what preserving the namespace is?
> 

- Original files are in DeltaV folders. They should be in _DeltaV folders on Harmony.
- c# files have `namespace` declaration. These should also keep DeltaV in the namespace and they mimic the filepaths

2024-12-12 00:16 UTC, FluffMe requested changes
Namespaces are very wrong.
Can't review in detail from the phone, but I'll fix it in the next couple of days or on the weekend, unless you figure it out sooner.

Check for harmony C#-containing PRs for reference, if need be.

2024-12-12 00:19 UTC, TheCrimsonJupiter commented
Does this replace the current kill/maroon objectives or does it add a new kind of objective for traitors? If it replaces them like they do on DeltaV, I foresee a big rule conflict and general bad vibes. 

There are many traitor tools and methods of killing that are designed to round remove, should this no longer ever be a requirement these sorts of tools will just be rulebreaks if they are used 
"Minor antagonists... should not: Actively round remove people not listed as targets by you or another syndicate." 
from Rule 5: Play Antagonists Responsibly. Should this feature REPLACE kill/maroon, like it does on DeltaV, then using any of these methods would be a rule violation and thats just bad game design to have features that conflict with our philosophy. Similar applies regardless of rules. Should somebody be murdered as a "teach a lesson" target and then fly off into space and be round removed, thats going to be far more upsetting than just being killed as a regular objective for you are now round removed even though you weren't required to be by the game. 

All of this doesn't really apply should it be added as a separate objective, for then discretion and use of tools can be scaled to the task at hand.

2024-12-12 00:30 UTC, TheCrimsonJupiter commented
> It does not replace kill and maroon, it is merely a diffreent alternative to add variety

In that case all I wrote was just nonsense rambling. I'm a-okay with this as a new objective, but I think the name should be changed "Teach (name) a lesson" doesn't make any sense. When somebody wakes up from being dead they shouldn't be remembering anything that happened, so there is no lesson being taught here. If there was something with leaving a business card on a dead person so they find it when they wake up maybe that'd make more sense, but that'd take some extra programming stuff that I don't know if anybody is interested in. Something like "Kill them once" would be very basic and not very interesting, but would be less vague and nonsense and get the idea across a million times better.

2024-12-15 18:10 UTC, FluffMe requested changes
First big bunch of required changes.

After you are done with this you should also implement https://github.com/DeltaV-Station/Delta-v/pull/2412 and test everything properly. Milon's PR also properly sets the DeltaV namespaces.

Trace any other changes or PRs to these files that might be important.

Once this work is done, please test it thoroughly and make sure to keep as much of DeltaV code intact as possible. If you make any changes you must declare them per AGPL licensing. No renaming of the files where it's not needed, etc.

This should be a lot of work for someone with no C# experience, so thank you for tackling this. Feel free to ask questions on Discord if you need help. Experienced contributors should be able to help you.

Good luck!

2024-12-15 18:10 UTC, FluffMe commented on Resources/Prototypes/Objectives/base_objectives.yml
> +
Unnecessary change to upstream file. Please revert.

2024-12-15 18:10 UTC, FluffMe commented on Resources/Prototypes/_Harmony/Objectives/base_objectives.yml
> +      - SocialObjective
This prototype should be declared in `traitor.yml` with `TeachLessonRandomPersonObjective` instead

2024-12-15 18:10 UTC, FluffMe commented on Resources/Prototypes/_Harmony/Objectives/traitor.yml
DeltaV content. Wrong location.
Should be `Resources/Prototypes/_DeltaV/Objectives/traitor.yml`

2024-12-15 18:10 UTC, FluffMe commented on Content.Server/_DeltaV/Objectives/Components/Teachalessonconditionststem.cs
> +using DeltaV.Server.Objectives.Components;
Not needed and wrong. Remove this line

2024-12-15 18:10 UTC, FluffMe commented on Content.Server/_DeltaV/Objectives/Components/Teachalessonconditionststem.cs
> +namespace DeltaV.Content.Server.Objectives.Systems;
```suggestion
namespace Content.Server.Objectives.Systems;
```

We'll just keep this simple and keep original DeltaV namespaces for this.

2024-12-15 18:10 UTC, FluffMe commented on Content.Server/_DeltaV/Objectives/Systems/TeachAlessonComponent.cs
> +namespace DeltaV.Server.Objectives.Components;
```suggestion
using Content.Server.Objectives.Systems;

namespace Content.Server.Objectives.Components;
```

2024-12-15 18:41 UTC, FluffMe commented
Marked as draft to avoid constant test runs on Work In Progress. Undraft when it's done.

2024-12-24 19:38 UTC, FluffMe commented
@Ermucat I see that you have requested a review, but the PR is in the draft state.
- Please undraft when it's ready.

2024-12-24 20:25 UTC, FluffMe requested changes
Please view and implement the requested changes.

As there is a discrepancy between this PR and DeltaV code in the yaml, please review one more time the code in DeltaV [master](https://github.com/DeltaV-Station/Delta-v/) vs this PR for the affected files. For good measure.

Should be the last batch of changes otherwise! Great job!

2024-12-24 20:25 UTC, FluffMe commented on Resources/Prototypes/_DeltaV/Objectives/traitor.yml
> +  - type: TeachLessonCondition
In https://github.com/DeltaV-Station/Delta-v/blob/master/Resources/Prototypes/DeltaV/Objectives/traitor.yml there is no `TeachLessonCondition` component in the `TeachLessonRandomPersonObjective` entity. Which makes sense, as it's defined in one of the parents -- `BaseTeachLessonObjective`.

Is it needed here?

2024-12-24 20:25 UTC, FluffMe commented on Content.Server/DeltaV/Objectives/Components/TeachLessonConditionComponent.cs
Please relocate to `Content.Server/_DeltaV/Objectives/Components/TeachLessonConditionComponent.cs` (missing `_` in `_DeltaV`)

2024-12-24 20:25 UTC, FluffMe commented on Content.Server/DeltaV/Objectives/Systems/TeachLessonConditionSystem.cs
Please relocate to `Content.Server/_DeltaV/Objectives/Systems/TeachLessonConditionSystem.cs` (missing `_` in `_DeltaV`)

2024-12-24 20:25 UTC, FluffMe commented on Resources/Prototypes/_DeltaV/Objectives/traitor.yml
> +  id: BaseTeachLessonObjective
Optional nitpick. Base is better located before the thing that inherits from it.

You can move it above `TeachLessonRandomPersonObjective`.

2024-12-24 20:39 UTC, FluffMe approved these changes

2024-12-25 22:23 UTC, merged