Adds poquito
ss14-harmony/space-station-14 pull request #235
Opened 2024-12-15 16:07 UTC by Ermucat

## About the PR

Adds Poquito which is a new pet, but Im pretty sure everything is in the wrong files and it all has to be mapped ):
## Why / Balance

This would just add more ghost roles I guess? If mapped of course
## Technical details

Just added stuff from files
## Media

https://github.com/user-attachments/assets/c430736b-3550-4cc6-aae9-9423eb72a40f

## Requirements

- [X ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- adds poquito the more mischievous version of pun pun

2024-12-15 16:13 UTC, FluffMe requested changes
* Yes, everything is in the wrong files.
* `Just added stuff from files` is not a very good technical description for me to go on. What stuff, from which files? Is this your code or attribution is needed?

2024-12-15 16:23 UTC, Ermucat commented
Fair enough

2024-12-15 17:45 UTC, FluffMe requested changes

2024-12-15 17:45 UTC, FluffMe commented on Resources/Prototypes/Entities/Markers/Spawners/mobs.yml
> +    - MobReindeerDoe
Upstream file still shows as edited with only change being an EoF empty line added.
Please revert this change.

2024-12-15 17:45 UTC, FluffMe commented on Resources/Prototypes/Roles/Jobs/Fun/misc_startinggear.yml
> +    id: PoquitoIDcard
* This prototype is already declared in `Resources/Prototypes/_Harmony/Roles/Jobs/Fun/misc_startinggear.yml`. Revert this change.

2024-12-15 17:45 UTC, FluffMe commented on Resources/Prototypes/_Harmony/Entities/Objects/Misc/identification_cards.yml
> +﻿# Harmony base ID card
It's not a base card. Either remove the comment, or state that this is a Poquito ID card

2024-12-15 17:45 UTC, FluffMe commented on Resources/Prototypes/_Harmony/Roles/Jobs/Fun/misc_startinggear.yml
> +﻿# Harmony gear?
No question mark in the comment. `# Harmony Poquito gear` should be good

2024-12-15 17:50 UTC, DieselMohawk commented
I would like to note that in all maps would need to maintained in order to add the spawner to them. This may be a bit much, but I suppose it's up to Spanky in the end.

2024-12-15 18:15 UTC, FluffMe commented
> I would like to note that in all maps would need to maintained in order to add the spawner to them. This may be a bit much, but I suppose it's up to Spanky in the end.

Admin spawn is also an option, ass spawner is available to them

2024-12-15 18:20 UTC, FluffMe requested changes

2024-12-15 18:20 UTC, FluffMe commented on Resources/Prototypes/Entities/Markers/Spawners/mobs.yml
> +    - MobReindeerDoe
This change from previous review is still not addressed.

2024-12-19 22:23 UTC, Ermucat commented
As far as Im aware ( SO not much ) I would have to make a new species indentical to a kobold but instead of random sprite use a diffrent way to make his sprite consistent.

2024-12-19 22:26 UTC, FluffMe commented
No, should be respritable by overriding stuff from base kobold in poquito prototype.

There are good spriters on Discord, if you need one to collaborate with. If memory doesn't fail me @Blackern5000 is a very good one too

2024-12-19 22:28 UTC, Ermucat commented
thats why Im not the smartest. But the sprites are there its just setting a kobold color and the ears and tail

2024-12-19 22:28 UTC, Ermucat commented
thanks for the help

2024-12-21 14:09 UTC, FluffMe requested changes
The change requested in previous 2 reviews is still not addressed.

2024-12-21 14:09 UTC, FluffMe commented on Resources/Prototypes/Entities/Markers/Spawners/mobs.yml
> +
Still modified upstream file for no reason

2024-12-21 14:51 UTC, closed without merging