Port of Delta V Vent critters
ss14-harmony/space-station-14 pull request #244
Opened 2024-12-25 01:14 UTC by Ermucat

## About the PR
Ported https://github.com/DeltaV-Station/Delta-v/pull/2495/files, which changes vent critters to
1. Choose one vent to spawn of
2. Gives a 15 second delay for crew to vacate
3. Scales with player count
## Why / Balance

Stops people from getting randomly murdered by a slime that spawned on top of them
## Technical details

Changes Vent Critter Component and Vent Critter Rule
changes duration to delay in events.yml and pests.yml
## Media

https://github.com/user-attachments/assets/d9189327-8bd3-47a7-a5df-7535977f0fea

## Requirements

- [ X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

2024-12-25 01:31 UTC, spanky-spanky commented
If it wasn't evident from the Discord discussion, this automatically has admin approval.

2024-12-25 01:31 UTC, Ermucat commented
That is good

2024-12-25 02:11 UTC, TheCrimsonJupiter commented
This is so damn cool!

2024-12-26 06:08 UTC, FluffMe commented
https://github.com/DeltaV-Station/Delta-v/pull/2517

This looks important to include?

2024-12-26 15:28 UTC, Ermucat commented
It is now implemented

2025-01-03 04:46 UTC, FluffMe commented on Resources/Prototypes/GameRules/events.yml
> +    duration: 50
Missing comment

2025-01-03 04:51 UTC, FluffMe commented on Resources/Prototypes/GameRules/pests.yml
> +        weight: 0.01
This is 1000 times more likely to spawn `MobSnailInstantDeath` now. DeltaV has it disabled entierly, which is signified by comment `no` but you didn't comment it out. Pick one:

- Keep upstream weight
- Disable like in DeltaV

2025-01-03 04:52 UTC, FluffMe commented on Resources/Prototypes/GameRules/pests.yml
> +      #- id: MobMouseCancer # DeltaV - no
Disables Cancer mouse spawn in the event. I am fine with that, I guess?

2025-01-03 05:05 UTC, FluffMe approved these changes
Code looks good now. Approved.

Couple of notes in general and for admin discussion:
- Cancer mouse and killer snail weights are set low, but it might bite us in the ass anyway, as logic to spawn stuff is changed now. DeltaV has those disabled.
- Code looks good but I can't test this for at lest a week. Someone and/or PR author should boot it up and run extensive testing on dev build.
- Calculation of number of critters to spawn might need to be tweaked for harmony pop. But it seems like a good formula on paper.

2025-01-03 05:06 UTC, FluffMe commented
@spanky-spanky i am removing approved by admin team label to address the above points.

2025-01-06 13:52 UTC, FluffMe requested changes
After some discussions, we would like the follwoing change to be made:
- Please remove cancer mouse and instant death snail from the pools by commenting it out (same as in DV codebase)

Thank you!

2025-01-06 15:05 UTC, FluffMe approved these changes

2025-01-06 15:19 UTC, merged

2025-01-07 16:07 UTC, Lyndomen commented
FYI Delta has run into some mapping issues where we have vents under tables, which then spawns 12 spiders trapped by said table. We're working to update our maps, you folks might wanna try the same.

2025-01-07 16:08 UTC, FluffMe commented
> FYI Delta has run into some mapping issues where we have vents under tables, which then spawns 12 spiders trapped by said table. We're working to update our maps, you folks might wanna try the same.

Thanks for the heads-up.

@spanky-spanky congratulations, figure out how to fix this XD