Security Department Resprite
ss14-harmony/space-station-14 pull request #257
Opened 2024-12-29 10:50 UTC by BoskiYourk

## About the PR

This is currently just a draft, I'll add all of the details later
## Why / Balance

All of the current security sprites were RIDDLED with inconsistencies and different colors, so I decided to resprite them.
## Technical details

See About the PR
## Media

![Sec Suits Geared](https://github.com/user-attachments/assets/61166f86-db88-44a0-882e-d62221ae4f0a)
![Sec Suits](https://github.com/user-attachments/assets/e7a9f155-5a62-4bd3-9bbb-73ed9ea93852)
![HoS Turtle](https://github.com/user-attachments/assets/f7995525-e2af-493a-8572-809dd46ddd08)
![Sec winter](https://github.com/user-attachments/assets/f90bfca1-dd2a-4b2d-98e7-8f0c44afb8ba)

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added the Head of Security's turtle neck and Senior Officer beret
- tweak: Resprited most of the basic security jumpsuits

2024-12-30 02:23 UTC, BoskiYourk commented
Things are failing now after I fully PR it, sad days.

2024-12-30 03:01 UTC, DieselMohawk requested changes
Notation updates required, sprites look good.

2024-12-30 19:47 UTC, FluffMe requested changes
Linter fail is real

Unhandled exception. NUnit.Framework.AssertionException: CLIENT: 13.986s [ERRO] go.comp.sprite: Unable to load RSI '/Textures/_Harmony/Clothing/Shoes/Boots/winterbootssec.rsi'.

Probably this is due to your RSI having lowercase boots in path. It's case sensitive.

2024-12-31 00:23 UTC, FluffMe commented
@BoskiYourk I'd rather you rename the folder to use capital letter to confirm with other paths in game, than changing it to lowercase in YAML

2024-12-31 00:23 UTC, BoskiYourk commented
> @BoskiYourk I'd rather you rename the folder to use capital letter to confirm with other paths in game, than changing it to lowercase in YAML

Yeah... I was trying to get it to work with the git mv command, but it didn't want to work, and I just felt laaaaaazy
I'll see what I can do, though

2025-01-01 07:50 UTC, BoskiYourk commented
Straight up forgor the meta file
I SWEAR I KNOW WHAT IM DOING!!

2025-01-01 08:02 UTC, BoskiYourk commented
Alright, I'm gonna need some external help with this. I'm unable to rename or delete the boots and winterbootssec.rsi file, so I can't change it's name. I'm just kinda lost and don't know what to do.

2025-01-01 13:06 UTC, FluffMe commented
> Alright, I'm gonna need some external help with this. I'm unable to rename or delete the boots and winterbootssec.rsi file, so I can't change it's name. I'm just kinda lost and don't know what to do.

Give me push access to
https://github.com/BoskiYourk/space-station-14/

2025-01-02 03:24 UTC, BoskiYourk commented
> > Alright, I'm gonna need some external help with this. I'm unable to rename or delete the boots and winterbootssec.rsi file, so I can't change it's name. I'm just kinda lost and don't know what to do.
> 
> Give me push access to https://github.com/BoskiYourk/space-station-14/

Should be sent. I have some more sprites and fixes to add after this is hopefully fixed, so I'll need to get those in.

2025-01-02 10:17 UTC, FluffMe commented
> > > Alright, I'm gonna need some external help with this. I'm unable to rename or delete the boots and winterbootssec.rsi file, so I can't change it's name. I'm just kinda lost and don't know what to do.
> > 
> > 
> > Give me push access to https://github.com/BoskiYourk/space-station-14/
> 
> Should be sent. I have some more sprites and fixes to add after this is hopefully fixed, so I'll need to get those in.

What do you need help with? Files are fine

![image](https://github.com/user-attachments/assets/a8775dfa-4a27-47eb-bfdf-a18ca3984a8d)

2025-01-02 10:20 UTC, FluffMe commented
Changed path to `_Harmony/Clothing/Shoes/Boots/winterbootssec.rsi` in YAML

2025-01-03 02:12 UTC, DieselMohawk requested changes
You failed me.

2025-01-03 02:12 UTC, DieselMohawk commented on Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_flasks.yml
Do not put an "s" after an apostrophe that's after an "s".

Minor grammar mistake :(

2025-01-03 02:24 UTC, BoskiYourk commented on Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_flasks.yml
I didn't change the name. It was like that before.

2025-01-03 02:26 UTC, BoskiYourk commented on Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_flasks.yml
I can fix it, though. Just give me a bit

2025-01-03 02:26 UTC, DieselMohawk commented on Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_flasks.yml
Fix it for me please, I can sort through the rest of the code for this shit.

2025-01-03 02:35 UTC, FluffMe commented on Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_flasks.yml
Why are we changing/fixing flask prototypes in a resprite PR, exactly?

2025-01-03 02:53 UTC, BoskiYourk commented on Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_flasks.yml
The hos's flask is a part of security gear in my eyes, and I resprited it for gits and shiggles, so I just added it to this PR

2025-01-03 03:00 UTC, FluffMe commented on Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_flasks.yml
It changes not only sprite, but also inheritance without even a comment on any of those those changes.

Arguably, it should be made contraband and grammar fixed upstream. Along with det flask etc in one PR to not have one as contra and other totally ok

But if you really want it, ok. Just comment the changes properly and verbose

2025-01-03 03:18 UTC, BoskiYourk commented on Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_flasks.yml
Ive always just stuck with Harmony for all of my resprites and alters, so I am just doing it here. Diesel said he'd PR the rest to here then upstream.

I totally spaced adding the rest of the changes to the original PR message because I so badly want to just be done with this PR. I'll get it here in a few minutes

2025-01-03 04:34 UTC, FluffMe requested changes
Bunch of stuff and qestions to go through.
Mostly removed empty lines that make separate entities readable.

I may have missed something as this is a rather large PR, but you get the idea from the ones I caught.

2025-01-03 04:34 UTC, FluffMe commented on Resources/Prototypes/Entities/Clothing/Shoes/boots.yml
> +    modifier: 0.5
Slow modifier changed. Not stated in the comment or PR details.
Does this affect ballance? Is this needed as a part of the resprite?

I see that intention is to be on par with regular jackboots, but double checking due to this not being stated anywhere else.

2025-01-03 04:34 UTC, FluffMe commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpskirts.yml
> +# Harmony Change: Updated Sprite Pathing, Name, and Description for Harmony Security Sprite Fixing Update
- Please add a new line between the previous entity and the comment for this entity
- Comment mentions the change in RSI path. **Path is not changed**

2025-01-03 04:34 UTC, FluffMe commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpskirts.yml
> +#Harmony Change: Updated Pathing for security resprite update
Please add a new line between the previous entity and the comment for this entity

2025-01-03 04:34 UTC, FluffMe commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpskirts.yml
> +#Harmony Change: Updated Pathing for security resprite update
- Please add a new line between the previous entity and the comment for this entity
- Missing the mention of the name change

2025-01-03 04:34 UTC, FluffMe commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpskirts.yml
> +#Harmony Change: Updated Pathing for security resprite update
Please add a new line between the previous entity and the comment for this entity

2025-01-03 04:34 UTC, FluffMe commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
> +# Harmony Change: Updated Sprite Pathing, Name, and Description for Harmony Security Sprite Fixing Update
- Please add a new line between the previous entity and the comment for this entity
- While you are at it, please fix the same issue on line 354 for `ClothingUniformJumpsuitHoSBlue`
- The comment states that the path is changed. **Path is not changed**

2025-01-03 04:34 UTC, FluffMe commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
> +#Harmony Change: Updated Pathing for security resprite update
Please add a new line between the previous entity and the comment for this entity

2025-01-03 04:34 UTC, FluffMe commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
> +#Harmony Change: Updated Pathing for security resprite update
- Please add a new line between the previous entity and the comment for this entity
- Doesn't mention the renaming

2025-01-03 04:34 UTC, FluffMe commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
> +#Harmony Change: Updated Pathing for security resprite update
Please add a new line between the previous entity and the comment for this entity

2025-01-03 04:34 UTC, FluffMe commented on Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_flasks.yml
> +  parent: [FlaskBase, BaseCommandContraband]
Entity is missing the comment for the Harmony change that mentions the Conraband status and resprite

2025-01-03 04:34 UTC, FluffMe commented on Resources/Prototypes/Loadouts/Jobs/Security/head_of_security.yml
> +  id: HeadofSecurityAssaultSuit # Harmony Change: Updated ID for HoS Clothing and Loadout Update
- Add old ID (`HeadofSecurityTurtleneck`) to the comment
OR
- keep the old loadout but comment it out, and add a new one in Harmony files. You already have a lot of stuff in `Resources/Prototypes/_Harmony/Loadouts/Jobs/Command/head_of_security.yml` anyway

2025-01-03 04:34 UTC, FluffMe commented on Resources/Prototypes/Loadouts/Jobs/Security/head_of_security.yml
> +  id: HeadofSecurityAssaultSkirt # Harmony Change: Updated ID for HoS Clothing and Loadout Update
- Add old ID (`HeadofSecurityTurtleneckSkirt`) to the comment
OR
- keep the old loadout but comment it out, and add a new one in Harmony files. You already have a lot of stuff in `Resources/Prototypes/_Harmony/Loadouts/Jobs/Command/head_of_security.yml` anyway

2025-01-03 04:34 UTC, FluffMe commented on Resources/Prototypes/Loadouts/loadout_groups.yml
> -  - HeadofSecurityTurtleneck
Keep upstream ID but comment it out.

2025-01-03 04:34 UTC, FluffMe commented on Resources/Prototypes/Loadouts/loadout_groups.yml
> -  - HeadofSecurityTurtleneckSkirt
Keep upstream ID but comment it out.

2025-01-03 04:36 UTC, BoskiYourk commented on Resources/Textures/_Harmony/Clothing/Head/Hats/warden.rsi/meta.json
> +  "copyright": "Made by CrimsonJupiter for use in Harmony. Icon taken from tgstation at commit https://github.com/tgstation/tgstation/commit/4f6190e2895e09116663ef282d3ce1d8b35c032e, texture edited b
Yup! It is

2025-01-03 10:22 UTC, BoskiYourk commented on Resources/Prototypes/Entities/Clothing/OuterClothing/wintercoats.yml
> -    clothingPrototype: ClothingHeadHatHoodWinterWarden
The coat isn't supposed to have a hood since it wasn't really designed with one, but since it seems un-removeable I'll be adding it.

2025-01-03 10:24 UTC, BoskiYourk commented on Resources/Prototypes/Entities/Clothing/Shoes/boots.yml
> +    modifier: 0.5
Yeah, with this PR cooking in the oven for how long as it has a lot has slipped my mind. Comment updated, and I will be adding all of the stuff I've missed to the original PR message.

2025-01-03 14:20 UTC, FluffMe requested changes
Should be last batch of changes!

2025-01-03 14:20 UTC, FluffMe commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpskirts.yml
> +  id: ClothingUniformJumpskirtHoSAlt # Old ID: HeadofSecurityTurtleneckSkirt
Both old and new IDs here are `ClothingUniformJumpskirtHoSAlt`. So no comment needed, or something is wrong.

2025-01-03 14:20 UTC, FluffMe commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
> +  id: ClothingUniformJumpsuitHoSAlt # Old ID: HeadofSecurityTurtleneck
Both old and new IDs here are `ClothingUniformJumpsuitHoSAlt`. So either no comment needed as there is no change, or something is wrong.

2025-01-03 14:20 UTC, FluffMe commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
> +  name: warden's jumpsuit
Comment still doesn't mention the renaming.

2025-01-03 14:20 UTC, FluffMe commented on Resources/Prototypes/Loadouts/Jobs/Security/head_of_security.yml
>      jumpsuit: ClothingUniformJumpsuitHoSAlt
Comment still doesn't mention old ID

2025-01-03 14:20 UTC, FluffMe commented on Resources/Prototypes/Loadouts/Jobs/Security/head_of_security.yml
>      jumpsuit: ClothingUniformJumpskirtHoSAlt
Comment still doesn't mention old ID

2025-01-05 04:13 UTC, DieselMohawk approved these changes
Sprites look good.

2025-01-06 14:07 UTC, FluffMe approved these changes

2025-01-06 14:07 UTC, merged