Makes poquito a real boy
ss14-harmony/space-station-14 pull request #258
Opened 2024-12-29 19:18 UTC by Ermucat

## About the PR

Implemented it so that poquito might spawn instead of alexander
## Why / Balance

Implementing un-implemented feature, up to the discretion of the maintaining team of course
## Technical details

Added Harmony tag to Alexanderspawner
## Media

https://github.com/user-attachments/assets/c7aabbca-5f47-430f-b4fd-704a851a91ca

## Requirements

- [X ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Made poquito naturally spawn in the kitchen

2024-12-29 19:20 UTC, spanky-spanky commented
Genius

2024-12-30 20:16 UTC, FluffMe requested changes
One unnecessary line change to get rid of.

2024-12-30 20:34 UTC, FluffMe requested changes
It's still there.

You need help murdering it?
You were struggling with those before.

2024-12-30 20:37 UTC, Ermucat commented
If you dont mind helping me murder it.

2024-12-30 20:38 UTC, FluffMe commented
> If you dont mind helping me murder it.

I'll need push access to https://github.com/Ermucat/GoonCave-14

2024-12-30 20:46 UTC, FluffMe commented
@Ermucat you can revoke my access

2024-12-30 20:46 UTC, FluffMe approved these changes

2025-01-08 01:41 UTC, KeldWolf approved these changes

2025-01-08 01:41 UTC, merged